/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Auto-generated classes from next-markdown-blog config
    "bg-gray-800",
    "border-gray-300",
    "border-l-4",
    "font-bold",
    "font-mono",
    "font-semibold",
    "h-auto",
    "hover:text-blue-800",
    "italic",
    "leading-relaxed",
    "list-decimal",
    "list-disc",
    "list-inside",
    "max-w-full",
    "mb-1",
    "mb-2",
    "mb-3",
    "mb-4",
    "mb-6",
    "mt-4",
    "mt-6",
    "mt-8",
    "my-4",
    "overflow-x-auto",
    "p-4",
    "pl-4",
    "px-1",
    "py-0.5",
    "rounded",
    "rounded-lg",
    "shadow-md",
    "text-2xl",
    "text-3xl",
    "text-4xl",
    "text-base",
    "text-blue-600",
    "text-gray-900",
    "text-lg",
    "text-red-500",
    "text-sm",
    "text-xl",
    "underline",
    "uppercase"
  ],
  theme: {
    extend: {},
  },
  plugins: [require('@tailwindcss/typography')],
};
