import { readFileSync, writeFileSync } from 'node:fs';
import type { NextMarkdownBlogConfig } from '../types/index.js';
import { generateTailwindConfig } from './tailwind-classes.js';

/**
 * Generates a Tailwind config file that includes the necessary safelist for next-markdown-blog
 * @param configPath - Path to the next-markdown-blog config file
 * @param outputPath - Path where to write the generated Tailwind config (optional)
 */
export function generateTailwindConfigFile(configPath: string, outputPath?: string): string {
  try {
    // Read the next-markdown-blog config
    const configContent = readFileSync(configPath, 'utf-8');

    // Parse the config (assuming it's a CommonJS module)
    const configModule = { exports: {} };
    // eslint-disable-next-line @typescript-eslint/no-implied-eval
    const configFunction = new Function('module', 'exports', 'require', configContent);
    configFunction(configModule, configModule.exports, require);

    const config = configModule.exports as NextMarkdownBlogConfig;

    // Generate Tailwind config with safelist
    const tailwindConfig = generateTailwindConfig(config.styleClasses);

    // Create the output content
    const outputContent = `// Auto-generated Tailwind config for next-markdown-blog
// This file was generated by next-markdown-blog to ensure all required classes are included
// Run this command to regenerate: npx next-markdown-blog generate-tailwind-config

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: ${JSON.stringify(tailwindConfig.safelist, null, 2)},
  theme: {
    extend: {},
  },
  plugins: [],
}
`;

    // Write to output path or return the content
    if (outputPath) {
      writeFileSync(outputPath, outputContent, 'utf-8');
      console.log(`✅ Tailwind config generated at: ${outputPath}`);
    }

    return outputContent;
  } catch (error) {
    throw new Error(
      `Failed to generate Tailwind config: ${error instanceof Error ? error.message : 'Unknown error'}`
    );
  }
}

/**
 * CLI function to generate Tailwind config
 */
export function generateTailwindConfigCLI() {
  const args = process.argv.slice(2);
  const configPath = args[0] || './next-markdown-blog.config.js';
  const outputPath = args[1] || './tailwind.config.js';

  try {
    generateTailwindConfigFile(configPath, outputPath);
    console.log('🎉 Tailwind config generated successfully!');
    console.log('📝 Make sure to update your Tailwind config to use the generated safelist.');
  } catch (error) {
    console.error(
      '❌ Error generating Tailwind config:',
      error instanceof Error ? error.message : 'Unknown error'
    );
    process.exit(1);
  }
}
